# This file is part of the Pattern Library Builder library.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 7.1

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

script:
    - vendor/bin/phpspec run -fpretty

cache:
    directories:
        - $COMPOSER_CACHE_DIR
